### ISSUE TITLE
support remix

### ISSUE THREAD

**Issue by gpBlockchain** [godwokenrises/godwoken-web3#285]
There are a few problems with adapt remix
### 1. An account with nonce of 0 can not be usded
![image](https://user-images.githubusercontent.com/32102187/163679249-4a817082-408a-4797-8b6d-d30e8ccc43b9.png)
### 2. The sent transaction must manually modify the gas value
![image](https://user-images.githubusercontent.com/32102187/163679496-e9f98a6b-7885-4052-afcd-25cee5ba85ca.png)
![image](https://user-images.githubusercontent.com/32102187/163679497-a0b5d43b-498b-41eb-a44e-ee47ce91a62e.png)
### 3. invoke revert tx ,can't return error message
![image](https://user-images.githubusercontent.com/32102187/163679741-dbbe4c43-0fad-4875-92ce-97c4958b144f.png)

### 4. forcibly send illegal transactions, remix will always be stuck in pending
![image](https://user-images.githubusercontent.com/32102187/163679652-54b378ad-e3ac-4836-b286-2860fc69eb71.png)
### 5. after Forcibly send illegal transactions,send a normal transaction will also return an illegal nonce
![image](https://user-images.githubusercontent.com/32102187/163679705-85a20906-d295-4c39-af6d-ef93d74bf2d9.png)

**Comment by Flouse** [comment]
I have used Remix to deploy a simple contract on Godwoken testnet_v1.
It works.

![image](https://user-images.githubusercontent.com/1297478/177789644-733e7498-2b76-40fb-8257-6324a4608cae.png)
![image](https://user-images.githubusercontent.com/1297478/177790189-cf96af54-9fed-4bf5-ad54-695a88ab6590.png)


## The network config of Godwoken testnet_v1
![image](https://user-images.githubusercontent.com/1297478/177790005-fc5bd677-e873-43df-9bd3-4d0759fca702.png)
