### ISSUE TITLE
[V1] - gw_get_account_id_by_script_hash return the account id even tho call methods still faill on blockchain 

### ISSUE THREAD

**Issue by Roger-RumbleFish** [godwokenrises/godwoken-web3#297]
I'm trying to make a flow for a user to create account on Godwoken and after the account is created process in application.

Here is a method for creating Godwoken account 

```
 /** Call a CKB send transaction from L1-L2 to create an account if it not exist.
   * Require for user to have ~470 ckb on L1
   * Need to be called in web with metamask installed */
  /** Local CKB has no default PWCore, no creation of Layer2 PW Address */
  async createLayer2Address(
    ethereumAddress: HexString,
    depositAmountInCkb = "400"
  ): Promise<string> {
    const depositAmountInShannons =
      CkbAmount.fromCkb(depositAmountInCkb).toString();

    const minimumCkbAmount = (
      BigInt(depositAmountInCkb) + BigInt("62")
    ).toString();

    const minimumAmountInShannons =
      CkbAmount.fromCkb(minimumCkbAmount).toString();

    await this.assertMinimumBalanceOfCkb(minimumAmountInShannons);

    const l2Address = await this.getLayer2DepositAddress(ethereumAddress);

    return this.sendCKB(depositAmountInShannons, l2Address);
  }

```

here is my code checking Godwoken accoun existt: 

```
  async checkLayer2AccountExist(ethereumAddress: HexString): Promise<boolean> {
    const script: Script = {
      code_hash: this._config.eth_account_lock_script_type_hash,
      hash_type: "type",
      args: this._config.rollup_type_hash + ethereumAddress.slice(2),
    };

    const userLockHash = utils.computeScriptHash(script);

    const name = "gw_get_account_id_by_script_hash";

    const result = await this._ckbRpc[name](userLockHash);
    return result !== null;
  }
```

and here is my code to wait for Godwoken account creation

```
  async waitForLayer2AccountCreation(
    ethereumAddress: HexString,
    interval: number = 5000,
    timeout?: number
  ): Promise<boolean> {
    let l2AccountCreated = false;
    let time = 0;

    while (!l2AccountCreated) {
      l2AccountCreated = await this.checkLayer2AccountExist(ethereumAddress);
      if (timeout && time > timeout) {
        console.log("timeout");
        throw new Error("Check layer 2 account timeout");
      }

      if (l2AccountCreated) {
        break;
      }

      await delay(interval);

      time += interval;
    }

    return l2AccountCreated;
  }

```
Steps:
1. I create a new MetaMask account
2. I use faucet https://faucet.nervos.org/ to provide ckb for my L1 address "OmniLock"
3. I run the method of `createLayer2Address` and then `waitForLayer2AccountCreation`
4. After 45 seconds or a bit more i receive the userId
5. To test if account exist i make a read call from signer  to a blockChain in my case

`  const signer = provider.getSigner(ethAddress)`

and then 

` contractsWithSigner?.registry.getAddressesProvidersList(),`

The call fail with 

![image](https://user-images.githubusercontent.com/82821191/163955077-d52a802e-ea4a-4672-b073-83bb8ecf8d90.png)

After some time 30 seconds to minute the call pass and account is created.

Why the block-chain not recognize the account even tho the id is returned by rpc method?

**Comment by Roger-RumbleFish** [comment]
When i wait 1 block after receiving the id it is working as expected

**Comment by RetricSu** [comment]
consider to be the same problem with #283, wait after removing the instant-finality feature to see if it is fixed.

**Comment by RetricSu** [comment]
hi, @Roger-RumbleFish  can you confirm this issue is also solved with #283 ?

**Comment by Flouse** [comment]
> consider to be the same problem with #283, wait after removing the instant-finality feature to see if it is fixed.

Hi, @Roger-RumbleFish 

After Godwoken Web3 v1.9+ , the the instant-finality feature is disabled by default, which is more compatible with Ethereum tool-chains.

## docs
- https://github.com/godwokenrises/godwoken-web3/blob/main/docs/addtional-feature.md

## Related PR
- refactor: instant-finality feature via special RPC url by @RetricSu in https://github.com/godwokenrises/godwoken-web3/pull/568

## Release
- https://github.com/godwokenrises/godwoken-web3/releases/tag/v1.9.0

**Comment by Flouse** [comment]
feel free to re-open this issue if you have any more question.
