### ISSUE TITLE
[get_code] 0x0000000000000000000000000000000000000000 return has no valid account_id

### ISSUE THREAD

**Issue by gpBlockchain** [godwokenrises/godwoken-web3#569]
env:https://godwoken-testnet-v1.ckbapp.dev 

hardhat upgrade  contract use uups  will call `eth_getCode` with (0x0) args ,because godwoken return failed ,make hardhat upgrade contract failed 

upgrade demo: https://github.com/OpenDefiContract/UUPSDemoContract.git

```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getCode',
  params: [ '0x0000000000000000000000000000000000000000', 'latest' ],
  id: 12
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 12,
  error: {
    code: -32099,
    message: 'zero address 0x0000000000000000000000000000000000000000 has no valid account_id! more info: https://github.com/nervosnetwork/godwoken-web3/blob/main/docs/compatibility.md'
  }
}
```
### expected 
should return 0x

**Comment by Flouse** [comment]
Related docs: 
https://github.com/godwokenrises/godwoken-web3/blob/1.8-rc/docs/compatibility.md#1-zero-address

**Comment by Dawn-githup** [comment]
fixed https://github.com/godwokenrises/godwoken-tests/pull/207

**Comment by Flouse** [comment]
https://github.com/godwokenrises/godwoken-web3/releases/tag/v1.9.0
